"""manual_add_cascade_delete

Revision ID: cd495f22435e
Revises: 46d3cf9edb8e
Create Date: 2025-06-27 06:55:54.673236

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cd495f22435e"
down_revision: Union[str, None] = "46d3cf9edb8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("route_days_route_id_fkey", "route_days", type_="foreignkey")
    op.create_foreign_key(
        None, "route_days", "routes", ["route_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "route_segments_route_day_id_fkey", "route_segments", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "route_segments",
        "route_days",
        ["route_day_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "route_segments", type_="foreignkey")
    op.create_foreign_key(
        "route_segments_route_day_id_fkey",
        "route_segments",
        "route_days",
        ["route_day_id"],
        ["id"],
    )
    op.drop_constraint(None, "route_days", type_="foreignkey")
    op.create_foreign_key(
        "route_days_route_id_fkey", "route_days", "routes", ["route_id"], ["id"]
    )
    # ### end Alembic commands ###
