"""add_spot_details_columns_to_rec_spot

Revision ID: 60045f7b5de9
Revises: 2bb5f9518cba
Create Date: 2025-06-25 05:42:53.529330+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60045f7b5de9'
down_revision = '2bb5f9518cba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rec_spot_coordinates', table_name='rec_spot')
    op.drop_index('idx_rec_spot_time_slot', table_name='rec_spot')
    op.drop_column('rec_spot', 'recommendation_reason')
    op.drop_column('rec_spot', 'time_slot')
    op.drop_column('rec_spot', 'latitude')
    op.drop_column('rec_spot', 'longitude')
    op.drop_column('rec_spot', 'selected')
    op.drop_column('rec_spot', 'google_map_image_url')
    op.drop_column('rec_spot', 'details')
    op.drop_column('rec_spot', 'website_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rec_spot', sa.Column('website_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('rec_spot', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('rec_spot', sa.Column('google_map_image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('rec_spot', sa.Column('selected', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('rec_spot', sa.Column('longitude', sa.NUMERIC(precision=11, scale=8), autoincrement=False, nullable=True))
    op.add_column('rec_spot', sa.Column('latitude', sa.NUMERIC(precision=10, scale=8), autoincrement=False, nullable=True))
    op.add_column('rec_spot', sa.Column('time_slot', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('rec_spot', sa.Column('recommendation_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('idx_rec_spot_time_slot', 'rec_spot', ['plan_id', 'version', 'time_slot'], unique=False)
    op.create_index('idx_rec_spot_coordinates', 'rec_spot', ['latitude', 'longitude'], unique=False)
    # ### end Alembic commands ### 